name: Deploy to Vercel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: team_hwILPbieGGX3JphkkS093dpl
          vercel-project-id: prj_FanJ35Niw2tYl91J6jay59lRW67R
          vercel-args: '--prod'
